version: '3.4'

services:
  todo.api:
    image: ${DOCKER_REGISTRY-}todo
    build:
      context: .
      dockerfile: src/Services/Todo/Todo.API/Dockerfile

  identity:
    image: ${DOCKER_REGISTRY-}identity
    build:
      context: .
      dockerfile: src/Services/Identity/Dockerfile

